### PR TITLE
Add Korean localization

### PR DESCRIPTION
**Pull request by josephnoir**
Related to #32

### CODE REVIEW

**Comment by josephnoir** [comment]
The diff also looks a bit weird. I will take a look tomorrow.

**Comment by jyothishjohnson** [comment]
Hi @josephnoir , I think there is no issues with the PR. The github workflow file has a timeout at 15 mins. Maybe that failed the pipeline. 
I will create a PR to update the workflow file.
cc @brittanyarima

**Comment by josephnoir** [comment]
Ah, I also checked the diff again. I think it just changes the order and it looks like the `bn` localization is replace in some places, but it just orders the languages alphabetically.

And if you say the file is just a timeout, all is good from my side!

**Comment by josephnoir** [comment]
Nice :)

**Pull request merged**
