### PR TITLE
Customizable Home Screen background

### PR DESCRIPTION
**Pull request by josephnoir**
### Issue 29: Ability for users to add their own image as Home Screen background

- Adds new section in the settings to select a photo to set as the background.
  - If the image is set if can be reset to the default image.
- This is realized via a `PhotosPicker` that asynchronously loads the image, compare this [sample code](https://developer.apple.com/documentation/photokit/bringing_photos_picker_to_your_swiftui_app).
- Adds functions to save, load, and delete a `UIImage` with a given `key` via `FileManager`.

### CODE REVIEW

**Comment by brittanyarima** [comment]
@josephnoir Thanks for this! There's just a few conflicts that I'll look into on Monday. But I'm excited to get this into the app!

**Comment by josephnoir** [comment]
I'll do a rebase when I get a chance. Maybe that will resolve the conflicts.

**Comment by josephnoir** [comment]
Oh, when I build it, `StepsCountView.swift` is missing from the project. The file exists, but it's not in Xcode. Looking at my diff of `Steps.xcodeproj/project.pbxproj` I did not delete it however. I added the file and it builds fine locally.

I tried to another rebase on dev, but it just seems to break things more. I think I somehow messed up the `project.pbxproj` file. Is there a way to resolve this without creating a clean branch from dev and apply the changes again?

**Comment by brittanyarima** [comment]
@josephnoir not you're fault at all. I've been having this same odd issue too! 😅 I've just been adding the file locally. If everything is building good on you're end, you can probably do that, merge dev into your branch & make sure everything still works, & if so, make another PR & I'll get it merged! 🙌 I'll look into why it keeps deleting these files from the project!

**Pull request closed without merging**
