### PR TITLE
58 extract viewmodels - 2

### PR DESCRIPTION
**Pull request by DandyLyons**
Sorry about the merge conflict. Here's another try. I hope that I've done it right this time. 

I don't want to retry the other two pull requests until I'm sure that this one is correct.

### CODE REVIEW

**Comment by DandyLyons** [comment]
From what I've read, .DS_Store is automatically created by macOS finder, is not relevant to the project, and can be safely ignored by git. I already added .DS_Store to the .gitignore, but it was after it already got recorded by an earlier commit and apparently git doesn't honor a .gitignore if it is already being tracked by that repo.

**Comment by brittanyarima** [comment]
@DandyLyons  Ok, try again. I had messed up when I was trying to resolve the merge conflict. For some reason it still wasn't using gitIgnore on the config files. But I think I fixed it! 

Sorry about all this! (First time maintaining during Hacktoberfest 😅)

**Comment by DandyLyons** [comment]
It's my first time participating in Hacktoberfest too. :D We're learning together! 

Let me know if there are any issues with this merge. If not, then I'll redo the other 2 merges using the same strategy.

**Comment by brittanyarima** [comment]
@DandyLyons oh that could be it! Let make know if you see anything on why this could be happening. If we can't figure it out, tomorrow I can  just merge, use your config files, and fix it on my end after it's merged.

**Comment by DandyLyons** [comment]
Also, in my research, I found out that if you add something to git ignore after it has already been tracked by the repo, then it won't ignore it. You have to call git rm --cached <filename> first.

**Comment by brittanyarima** [comment]
@DandyLyons that makes sense! It's been working for other people so far, so not sure why it's not on this. So odd! 🤔 I'm looking into it a bit right now!

**Comment by brittanyarima** [comment]
@DandyLyons I'm gonna ask someone to help & see if they can help me make sure all my gitIgnore's are setup right!

**Comment by brittanyarima** [comment]
@DandyLyons I think I fixed it! You were so right. I called git rm --cached. Try updating from dev again!

**Comment by DandyLyons** [comment]
I'm sorry. I'm not sure what you mean by "Try updating from dev again". I want to make sure I don't assume anything so that I don't make a mistake and create more work for you. 

Is [58 extract viewmodels - 2](https://github.com/brittanyarima/Steps/pull/62#top) done now? 

Do you mean you would like me to pull from dev and redo the other two PR's?

**Comment by brittanyarima** [comment]
No problem at all (I could’ve been clearer!)

Yeah, if you could merge the dev branch into your branch & make sure there
aren’t any merge conflicts then redo the PR. I cleared the cache on the
repo so I’m hoping this would make sure all the gitignore files are
actually ignored.

No matter what, tomorrow I have a bit more time so I should be able to get
your PRs merged and working smooth!

**Comment by DandyLyons** [comment]
I'm sorry, I tried to merge the dev branch into my `58 extract viewmodels - 2` branch and I fear I just made it worse. 

When I tried to redo the PR, it said that I couldn't do it because there were no changes in the PR. Sure enough my merge removed all my changes.

**Comment by brittanyarima** [comment]
@DandyLyons  oh shoot. I'm sorry! Worst case -- I can go back in and manually add your changes on the dev branch.

**Comment by brittanyarima** [comment]
@DandyLyons I'll do that later tonight!

**Comment by brittanyarima** [comment]
@DandyLyons  Added this manually to dev & moving on to your other two PRs!

**Comment by DandyLyons** [comment]
I think the problem was that I should have rebased to dev rather than merge. That way I could have the new changes from dev without losing my changes.

**Comment by DandyLyons** [comment]
I discovered an issue with `git rm --cached`. Yes the file is removed from git tracking, and yes the file is kept in your working directory, but since it's not tracked, it gets removed every time you switch branches. 

So now, when I go to branch dev, I lose my xcconfig files.

**Pull request merged**
